name: 'Electron Build Linux'
description: 'Build Electron app for Linux (AppImage)'

inputs:
  version:
    description: 'Version string for artifact naming'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache Electron Builder
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
        key: ${{ runner.os }}-electron-builder-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-builder-

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libgtk-3-0 \
          libgbm1 \
          libasound2t64 \
          libxshmfence1 \
          wget \
          ca-certificates \
          fonts-liberation \
          libappindicator3-1 \
          xdg-utils

    - name: Build AppImage
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          npm version ${{ inputs.version }} --no-git-tag-version
        fi
        npx electron-builder --linux AppImage
      env:
        DEBUG: electron-builder
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Generate SHA256 checksum
      shell: bash
      run: |
        cd release
        VERSION="${{ inputs.version }}"
        if [ -z "$VERSION" ]; then
          VERSION="$(node -p "require('../package.json').version")"
        fi
        sha256sum focus-${VERSION}.AppImage > focus-${VERSION}.AppImage.sha256sum
        cat focus-${VERSION}.AppImage.sha256sum

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: focus-linux-appimage
        path: release/
        retention-days: 7
        compression-level: 9
