name: 'Extract Version'
description: 'Extract version from PR commits and verify on merge commit'

inputs:
  base_sha:
    description: 'PR base SHA'
    required: true
    default: ''
  head_sha:
    description: 'PR head SHA'
    required: true
    default: ''

outputs:
  version:
    description: 'Extracted version (without v prefix)'
    value: ${{ steps.version.outputs.version }}
  is_release:
    description: 'Whether this is a release build'
    value: ${{ steps.version.outputs.is_release }}

runs:
  using: 'composite'
  steps:
    - name: Extract version from PR commits and verify on merge commit
      id: version
      shell: bash
      run: |
        # Get the merge commit SHA
        MERGE_SHA=$(git rev-parse HEAD)
        echo "Merge commit SHA: $MERGE_SHA"

        # Get PR commit range
        BASE_SHA="${{ inputs.base_sha }}"
        HEAD_SHA="${{ inputs.head_sha }}"
        echo "PR range: $BASE_SHA..$HEAD_SHA"

        # Check if merge commit already has a version tag
        MERGE_TAGS=$(git tag --points-at "$MERGE_SHA" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || echo "")
        if [ -n "$MERGE_TAGS" ]; then
          VERSION=${MERGE_TAGS#v}
          echo "Found version tag on merge commit: v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_release=true" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
          echo "Is Release: true"
          exit 0
        fi

        # Search for version tag in PR commits (in reverse order - newest first)
        echo "Searching for version tag in PR commits..."
        PR_COMMITS=$(git log --format="%H" "$BASE_SHA" ^"$HEAD_SHA" 2>/dev/null || git log --format="%H" "$BASE_SHA..$HEAD_SHA")

        VERSION=""
        for commit in $PR_COMMITS; do
          # Get tags pointing to this commit
          TAGS=$(git tag --points-at "$commit" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || echo "")
          if [ -n "$TAGS" ]; then
            VERSION=${TAGS#v}
            echo "Found version tag v$VERSION on commit $commit"
            break
          fi
        done

        if [ -n "$VERSION" ]; then
          echo "Error: Version tag v$VERSION exists in PR commits but NOT on merge commit"
          echo "Please tag the merge commit before merging:"
          echo "  git tag -a v$VERSION -m \"Release v$VERSION\" $MERGE_SHA"
          echo "  git push origin v$VERSION"
          exit 1
        else
          echo "No version tag found in PR commits"
          echo "version=" >> $GITHUB_OUTPUT
          echo "is_release=false" >> $GITHUB_OUTPUT
          echo "Version: (none)"
          echo "Is Release: false"
        fi

    - name: Verify version format
      if: steps.version.outputs.is_release == 'true'
      shell: bash
      run: |
        if ! [[ ${{ steps.version.outputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Version must be in format X.Y.Z (semantic versioning)"
          exit 1
        fi
        echo "Build version: ${{ steps.version.outputs.version }}"
