name: 'Electron Build Windows'
description: 'Build Electron app for Windows (EXE portable)'

inputs:
  version:
    description: 'Version string for artifact naming'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build Windows EXE
      shell: bash
      run: |
        npx electron-builder --win portable \
          --config.from=package.json \
          --build-version=${{ inputs.version }} \
          --config.publish=null
      env:
        DEBUG: electron-builder
        # Code signing configuration (for production, set these secrets)
        # CSC_LINK: ${{ secrets.WINDOWS_CERTIFICATE }}
        # CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        # CSC_FILES_LINK: ${{ secrets.WINDOWS_CERTIFICATE }}
    
    - name: Generate SHA256 checksum
      shell: pwsh
      run: |
        Get-FileHash -Algorithm SHA256 "release/focus-v${{ inputs.version }}-windows.exe" | ForEach-Object { $_.Hash } > "release/focus-v${{ inputs.version }}-windows.exe.sha256sum"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: focus-windows-exe
        path: release/
        retention-days: 7
