name: 'Electron Build macOS'
description: 'Build Electron app for macOS (DMG)'

inputs:
  version:
    description: 'Version string for artifact naming'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build DMG
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          npm version ${{ inputs.version }} --no-git-tag-version
        fi
        npx electron-builder --mac dmg
      env:
        DEBUG: electron-builder
        CSC_IDENTITY_AUTO_DISCOVERY: false
        # Code signing configuration (for production, set these secrets)
        # CSC_LINK: ${{ secrets.MACOS_CERTIFICATE }}
        # CSC_KEY_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
    
    - name: Generate SHA256 checksum
      shell: bash
      run: |
        cd release
        VERSION="${{ inputs.version }}"
        if [ -z "$VERSION" ]; then
          VERSION="$(node -p "require('../package.json').version")"
        fi
        if command -v sha256sum &> /dev/null; then
          sha256sum focus-${VERSION}.dmg > focus-${VERSION}.dmg.sha256sum
        else
          shasum -a 256 focus-${VERSION}.dmg > focus-${VERSION}.dmg.sha256sum
        fi
        cat focus-${VERSION}.dmg.sha256sum
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: focus-macos-dmg
        path: release/
        retention-days: 7
        compression-level: 9
