name: 'Prepare Release'
description: 'Prepare release assets and create GitHub release'

inputs:
  version:
    description: 'Version string'
    required: true

outputs:
  release_notes:
    description: 'Formatted release notes'
    value: ${{ steps.release_notes.outputs.content }}

runs:
  using: 'composite'
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v7
      with:
        path: release

    - name: Prepare release assets
      shell: bash
      run: |
        cd release
        # Flatten artifacts from subdirectories
        for dir in focus-*-*; do
          if [ -d "$dir" ]; then
            mv "$dir"/* .
            rmdir "$dir"
          fi
        done
        ls -la

    - name: Generate release notes
      id: release_notes
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        CHECKSUMS=$(cat release/*.sha256sum 2>/dev/null || echo "Checksums available in individual artifact downloads")
        
        # Read template and substitute placeholders using sed
        CONTENT=$(sed -e "s|{{VERSION}}|$VERSION|g" \
                      -e "s|{{CHECKSUMS}}|$CHECKSUMS|g" \
                      "${{ github.workspace }}/.github/release-notes.template.md")
        
        echo "content=$CONTENT" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: F.O.C.U.S. Assessment v${{ inputs.version }}
        tag_name: v${{ inputs.version }}
        draft: false
        prerelease: false
        files: release/*
        body: ${{ steps.release_notes.outputs.content }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
